name: OpenHarmony gitee repos mirror periodic job
on:
  schedule:
    # Runs at 20:00 UTC (4:00 AM Beijing) every day
    - cron:  '0 20 * * *'
  repository_dispatch:
    types:
      - humen_api_trigger
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Cache bare repo data
      uses: actions/cache@v2
      with:
        path: ${{ github.workspace }}/hub-mirror-cache
        key: ${{ runner.os }}-bare-repo-cache
        
    - name: Mirror the gitee/openharmony org repos to github/openharmony-gitee-mirror.
      uses: OpenHarmonySCM-noreply/hub-mirror-action@master
      with:
        src: gitee/openharmony
        dst: github/openharmony-gitee-mirror
        dst_key: ${{ secrets.SYNC_EG_PRIVATE_KEY }}
        dst_token:  ${{ secrets.SYNC_EG_TOKEN }}
        #static_list: 'installer'
        account_type: org
        clone_style: ssh
        force_update: true
        timeout: 30m
        cache_path: /github/workspace/hub-mirror-cache
    - name: Print cache path
        run:|
          ls -la ${{ github.workspace }}/hub-mirror-cache

